CLIP_PLAY_TIME: 10
CLIP_START_INTERVAL:
- 15
- 105
CUSTOMER_PO_TOKEN:
  po_token: ''
  visitor_data: ''
DEFAULT_COMMENT_PLACEHOLDERS: true
DOWNLOADER: bilibili
DOWNLOAD_HIGH_RES: false
FULL_LAST_CLIP: false
HTTP_PROXY: 127.0.0.1:7890
NO_BILIBILI_CREDENTIAL: false
ONLY_GENERATE_CLIPS: false
PROXY_ADDRESS: 127.0.0.1:7890
SEARCH_MAX_RESULTS: 3
SEARCH_WAIT_TIME: !!python/tuple
- 3
- 5
USER_ID: asdfasdf99
USE_ALL_CACHE: false
USE_AUTO_PO_TOKEN: true
USE_CUSTOM_PO_TOKEN: false
USE_OAUTH: false
USE_PROXY: false
VIDEO_RES:
- 1920
- 1080
VIDEO_TRANS_ENABLE: true
VIDEO_TRANS_TIME: 1.5
